### ISSUE TITLE
Could you explain how make_weights compute Q(y)/P(y|z)?

### ISSUE THREAD

**Issue by pruksmhc** [ghzhang233/Non-Discrimination-Learning-for-Text-Classification#6]
Thank you for making the code available! I was wondering, can you explain from [this line ](https://github.com/ghzhang233/Non-Discrimination-Learning-for-Text-Classification/blob/d8f945cd21c1b4f4b4498b9840f5d75bdd8d77c4/Toxicity%20Comments/make_weights.py#L73)onwards, how the weights are computed? I'm not super clear (from my understanding, a = Q(y = 0) and b = Q(y= 1), and propensity = p(y|z). 
Secondly, the code currently causes weights to have nans, which happens when there exists a 0 in propensity.

**Comment by ghzhang233** [comment]
Hi, @pruksmhc , Thank you for your interest in our work! 

For your first question, propensity = p(y|z), but the variables _a_ and _b_ are a little tricky. We make weights divided by _a_ and _b_ to make the prior probability of the weighted distribution the same as the original one. Consider the following line,
`a = np.mean(np.array([weights[i] for i in range(len(weights)) if y[i] == 0]))`
it's equivalent to 
`a = np.sum(np.array([weights[i] for i in range(len(weights)) if y[i] == 0])) / np.sum(y == 0)`
You can imagine such a process that, we want the sum of weights for both y = 0 and y = 1 to be one firstly, and then we multiply them with the original prior probability (_np.sum(y == 0) represents unnormalized prior probability_). The benefit of aligning the prior probability is to make sure the comparison reported in the paper is fair. On the other hand, in practical, you can just take Q(Y) as a hyper-parameter.

For your second question, I personally did not meet such a problem, but I believe this could happen sometimes. I think a simple solution is to add a smooth term like the following.
`weights = 1 / ((1-**0.001**) * propensity + **0.001**)`
The different smooth terms may yield different performances. Still, you can take it as a hyper-parameter.

**Comment by pruksmhc** [comment]
Alright, that makes a bit more sense. What do you mean by aligning the prior probability?

**Comment by ghzhang233** [comment]
@pruksmhc Aligning the prior probability means to make the prior probability of the weighted distribution the same as the original unweighted distribution.

**Comment by pruksmhc** [comment]
Alright, so it's been a while since I've done Bayesian probability, but from my derivations, the weight for (y_i, x_i, z_i) such that y_i = 0 is equal to (in your code, without the last part about weights /= weights.mean()), is:
<img width="732" alt="Screen Shot 2020-10-22 at 8 36 52 PM" src="https://user-images.githubusercontent.com/10094008/96953631-636ac380-14a6-11eb-90b1-156ce556fc28.png">
where N_0 = |B_0|, and B_0 is the set of examples in the biased dataset such with label 0. 
I'm not super clear about how the above is equal to P(y==0)/P(y_i|z_i). 
Thanks for your patience and being super responsive! I'm interested to use your method on some experiments that I'm currently running, but want to make sure I understand it fully.

**Comment by ghzhang233** [comment]
Hi, @pruksmhc , As I mentioned before, N_0 and N_1 are unnormalized prior probability as _P(Y=0) = N0 / (N0 + N1)_, _P(Y=1) = N1 / (N0 + N1)_. 

For the term 
![image](https://user-images.githubusercontent.com/15927725/96969146-95cafe00-1544-11eb-88a6-c2244bb7df7f.png), this is to make the prior probabilities aligned. With this term, the following equation can be satisfied.
![image](https://user-images.githubusercontent.com/15927725/96969600-45a06b80-1545-11eb-9762-f0e63b563ba8.png)
This is to make the comparison reported in the paper fair because the impacts of the prior probabilities can be eliminated. On the other hand, as I mentioned in the paper, you can just take Q(Y) as a hyper-parameter. The choice of Q(Y) is quite flexible, and
you can even simply ignore this term and N0 in practice.

Let me know if I failed to make it clear. I am happy to help!

**Comment by ghzhang233** [comment]
![image](https://user-images.githubusercontent.com/15927725/96971571-e42dcc00-1547-11eb-8bf3-782232082aff.png)
This is the whole derivation.
