### ISSUE TITLE
Classifier always predicting 0

### ISSUE THREAD

**Issue by Ago3** [ghzhang233/Non-Discrimination-Learning-for-Text-Classification#8]
Hi,

I'm still trying to replicate your scores, but somehow the baseline model always predicts '0', resulting in the following scores:

  | acc_dev | auc_dev | acc_test | auc_test | acc_eec | auc_eec | efpr_eec | efnr_eec | eauc_eec
0.83347107 | 0.83646156 | 0.82347107 | 0.82892792 | 0.52083333 | 0.78295652 | 0 | 0 | 0.07971772

I was wondering the following:
1) how do you handle padding? Because in the model file, mask_zero is set to False, and there is no explicit mention of the padding being appended in front of the sequences.
2) do you have any other idea about where this error might come from?

Thank you!
Agostina

**Comment by ghzhang233** [comment]
Hi, @Ago3 . Which dataset are you running at? Anyway, the AUC seems to be too low. Especially for the AUC_EEC, it's nearly 0.5! It means that the model is randomly guessing in EEC. As a result, the model will have no discrimination in EEC as you observed (because the model is just guessing). For padding, I initially set mask_zero to False because I intended to use CudnnLSTM at that time. I don't think this will result in the current irregular results.

**Comment by ghzhang233** [comment]
Hi, @Ago3 . For the padding, I initially set mask_zero to False because I intended to use CudnnLSTM then. I don't think this can result in the current irregular results. I am sorry that I also have no idea how this error might come from. I may need a few days to check the codes.

**Comment by ghzhang233** [comment]
BTW, which dataset are you running at? It is Sexist Tweets?

**Comment by ghzhang233** [comment]
Hi, @Ago3 . I just re-ran the codes out of the box and got the following results, which are consistent with those reported in the paper. So I guess there may be some problems with the data you used.
![image](https://user-images.githubusercontent.com/15927725/98079280-7a4de480-1eae-11eb-8e8a-75fe83c2430f.png)

**Comment by ghzhang233** [comment]
> Hi, @Ago3 . I just re-ran the codes out of the box and got the following results, which are consistent with those reported in the paper. So I guess there may be some problems with the data you used.
> ![image](https://user-images.githubusercontent.com/15927725/98079280-7a4de480-1eae-11eb-8e8a-75fe83c2430f.png)

These are the results with the Sexist Tweets dataset.

**Comment by Ago3** [comment]
Hi!

Yes, I'm using the Sexist Tweets dataset. Basically, I just created a csv file (starting from the json downloaded from Twitter) containing the text and the label of the tweets, with no extra preprocessing.. Is this wrong? I couldn't find explicit indications on how to preprocess the json, I just checked the code for understanding the expected format.

Did you just re-run the code for the baseline by keeping mask_zero set to False?

Thank you,
Agostina

**Comment by ghzhang233** [comment]
Hi, @Ago3 . Yes, I just downloaded the code from Github and ran it without any modification. How did you download the dataset from Twitter? It seems that Twitter deletes those abusive tweets regularly, so I guess maybe there are some problems here.

**Comment by Ago3** [comment]
Hi @ghzhang233 ,

Downloading data from Twitter wasn't a problem, I managed to get all the tweets you used for the task.

I noticed that the madlib.csv file uploaded in this repo is way bigger than the one I obtained by running the functions specified in the README. Do you have any idea of why it is so?

Anyway, even when using the csv file included in the repo I keep obtaining results that are way lower than yours. Here is what I get (R columns) side by side with the results from your paper (P columns).

<img width="431" alt="Screenshot 2020-11-09 at 17 44 44" src="https://user-images.githubusercontent.com/30800478/98577126-6857b180-22b3-11eb-824b-e4b472ba6bd5.png">

Do you have any idea of what could be wrong?

Thanks!

**Comment by ghzhang233** [comment]
Hi, @Ago3 .

For madlib.csv, it's because that we also add some semantic-neutral sentences provided by Dixon et al. (2018) to make sentences longer, as stated in appendix C in the paper. You can achieve this by adding _-longer_ parameter.

For the results, it's quite weird. Firstly, I would like to mention that some numerical fluctuations are hard to prevent because of the high inter-example variance of IPTTS, as stated in https://arxiv.org/abs/2004.13606. On the other hand, the results, in my personal opinion, are still very strange. I also don't have a specific idea about why this happened, but it seems that the models' performance also drops a lot comparing with our results in the paper. As I stated in the paper, models can achieve low FPED and FNED by making trivial predictions, so maybe this is the reason (_I am not sure, just maybe_).

Regards
